#:schema node_modules/wrangler/config-schema.json
name = "agencia-zutra"
compatibility_date = "2024-04-03"
pages_build_output_dir = "./dist"

[vars]
# Required: BREVO_API_KEY, BREVO_LIST_ID, PUBLIC_GTM_ID, PUBLIC_RECAPTCHA_SITE_KEY
# Contentful variables
CONTENTFUL_SPACE_ID = ""
CONTENTFUL_ACCESS_TOKEN = ""
CONTENTFUL_PREVIEW_TOKEN = ""
CONTENTFUL_ENVIRONMENT = "master"
CONTENTFUL_USE_PREVIEW = "false"
