#:schema node_modules/wrangler/config-schema.json
name = "agencia-zutra"
compatibility_date = "2024-04-03"
pages_build_output_dir = "./dist"

[vars]
# Required: BREVO_API_KEY, BREVO_LIST_ID, PUBLIC_GTM_ID, PUBLIC_TURNSTILE_SITE_KEY, TURNSTILE_SECRET_KEY
# (Las variables de Contentful se leerán automáticamente desde el Dashboard de Cloudflare)